def on_a_pressed():
    global spacePlan
    spacePlan = sprites.create_projectile_from_sprite(img("""
            . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . .
        """),
        bogey,
        200,
        200)
controller.A.on_event(ControllerButtonEvent.PRESSED, on_a_pressed)

def on_on_overlap(sprite2, otherSprite2):
    otherSprite2.destroy()
    scene.camera_shake(4, 500)
    info.change_life_by(-1)
sprites.on_overlap(SpriteKind.player, SpriteKind.enemy, on_on_overlap)

def on_life_zero():
    info.set_score(info.score())
    game.over(False, effects.slash)
info.on_life_zero(on_life_zero)

def on_on_overlap2(sprite, otherSprite):
    otherSprite.destroy(effects.spray, 500)
sprites.on_overlap(SpriteKind.projectile, SpriteKind.enemy, on_on_overlap2)

bogey: Sprite = None
spacePlan: Sprite = None
spacePlan = sprites.create(img("""
        ..fff.........777777....
            ..79ff.......7ff8877....
            ..799ff...777ffff77.....
            ..7899ffff88889999ff....
            ..7889ff8888888899b9f...
            ..c78888888888888b999f..
            .c88f888888888b11199b8f.
            788fffffff888899111b888f
            77777ff888f8888888888887
            .....788889988888888887.
            ....78888997f888888877..
            ...f8888997777777777....
            ...f8888f777f87.........
            ...777777778ff7.........
            .......77778f7..........
            ........77777...........
    """),
    SpriteKind.player)
spacePlan.set_position(0, 60)
controller.move_sprite(spacePlan, 0, 35)
spacePlan.set_stay_in_screen(True)
info.set_life(3)
info.set_score(0)
speed = -70

def on_update_interval():
    global speed, bogey
    speed += -5
    bogey = sprites.create(img("""
            ....................
                    ....................
                    ....................
                    ....................
                    ....................
                    ....eee.............
                    ...eeeee............
                    ..eeee4ee...e.......
                    ..ceeee4ee..e4......
                    ..ceeeee4eecee......
                    ..ceeeeeeeccee......
                    ..ceeeeeee..ee......
                    ..cceeeee...e.......
                    ...cceee............
                    ....cee.............
                    ....................
                    ....................
                    ....................
                    ....................
                    ....................
        """),
        SpriteKind.enemy)
    bogey.set_velocity(speed, 0)
    bogey.set_position(160, randint(10, 100))
    bogey.set_flag(SpriteFlag.AUTO_DESTROY, True)
    info.change_score_by(1)
game.on_update_interval(1000, on_update_interval)
