controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    spacePlan = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, bogey, 200, 200)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite2, otherSprite2) {
    otherSprite2.destroy()
    scene.cameraShake(4, 500)
    info.changeLifeBy(-1)
})
info.onLifeZero(function () {
    game.over(false, effects.slash)
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    otherSprite.destroy(effects.spray, 500)
    info.changeScoreBy(1)
})
let bogey: Sprite = null
let spacePlan: Sprite = null
spacePlan = sprites.create(img`
    ..ccc.........ffffff....
    ..f4cc.......fcc22ff....
    ..f44cc...fffccccff.....
    ..f244cccc22224442cc....
    ..f224cc2222222244b9c...
    ..cf2222222222222b999c..
    .c22c222222222b11199b2c.
    f22ccccccc222299111b222c
    fffffcc222c222222222222f
    .....f2222442222222222f.
    ....f222244fc2222222ff..
    ...c222244ffffffffff....
    ...c2222cfffc2f.........
    ...ffffffff2ccf.........
    .......ffff2cf..........
    ........fffff...........
    `, SpriteKind.Player)
spacePlan.setPosition(0, 60)
controller.moveSprite(spacePlan, 0, 35)
spacePlan.setStayInScreen(true)
info.setLife(3)
game.onUpdateInterval(1000, function () {
    bogey = sprites.create(img`
        ....................
        ....................
        ....................
        ....................
        ....................
        ....eee.............
        ...eeeee............
        ..eeee4ee...e.......
        ..ceeee4ee..e4......
        ..ceeeee4eecee......
        ..ceeeeeeeccee......
        ..ceeeeeee..ee......
        ..cceeeee...e.......
        ...cceee............
        ....cee.............
        ....................
        ....................
        ....................
        ....................
        ....................
        `, SpriteKind.Enemy)
    bogey.setVelocity(-100 + -50, 0)
    bogey.setPosition(160, randint(10, 100))
    bogey.setFlag(SpriteFlag.AutoDestroy, true)
})
