def on_a_pressed():
    global spacePlan
    spacePlan = sprites.create_projectile_from_sprite(img("""
            . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . .
        """),
        bogey,
        200,
        200)
controller.A.on_event(ControllerButtonEvent.PRESSED, on_a_pressed)

def on_on_overlap(sprite2, otherSprite2):
    otherSprite2.destroy()
    scene.camera_shake(4, 500)
    info.change_life_by(-1)
sprites.on_overlap(SpriteKind.player, SpriteKind.enemy, on_on_overlap)

def on_life_zero():
    game.over(False, effects.slash)
info.on_life_zero(on_life_zero)

def on_on_overlap2(sprite, otherSprite):
    otherSprite.destroy(effects.spray, 500)
    info.change_score_by(1)
sprites.on_overlap(SpriteKind.projectile, SpriteKind.enemy, on_on_overlap2)

bogey: Sprite = None
spacePlan: Sprite = None
spacePlan = sprites.create(img("""
        ..ccc.........ffffff....
            ..f4cc.......fcc22ff....
            ..f44cc...fffccccff.....
            ..f244cccc22224442cc....
            ..f224cc2222222244b9c...
            ..cf2222222222222b999c..
            .c22c222222222b11199b2c.
            f22ccccccc222299111b222c
            fffffcc222c222222222222f
            .....f2222442222222222f.
            ....f222244fc2222222ff..
            ...c222244ffffffffff....
            ...c2222cfffc2f.........
            ...ffffffff2ccf.........
            .......ffff2cf..........
            ........fffff...........
    """),
    SpriteKind.player)
spacePlan.set_position(0, 60)
controller.move_sprite(spacePlan, 0, 35)
spacePlan.set_stay_in_screen(True)
info.set_life(3)

def on_update_interval():
    global bogey
    bogey = sprites.create(img("""
            ....................
                    ....................
                    ....................
                    ....................
                    ....................
                    ....eee.............
                    ...eeeee............
                    ..eeee4ee...e.......
                    ..ceeee4ee..e4......
                    ..ceeeee4eecee......
                    ..ceeeeeeeccee......
                    ..ceeeeeee..ee......
                    ..cceeeee...e.......
                    ...cceee............
                    ....cee.............
                    ....................
                    ....................
                    ....................
                    ....................
                    ....................
        """),
        SpriteKind.enemy)
    bogey.set_velocity(-100 + -50, 0)
    bogey.set_position(160, randint(10, 100))
    bogey.set_flag(SpriteFlag.AUTO_DESTROY, True)
game.on_update_interval(1000, on_update_interval)
