controller.A.onEvent(ControllerButtonEvent.Pressed, function on_a_pressed() {
    
    spacePlan = sprites.createProjectileFromSprite(img`
            . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . .
        `, bogey, 200, 200)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function on_on_overlap(sprite2: Sprite, otherSprite2: Sprite) {
    otherSprite2.destroy()
    scene.cameraShake(4, 500)
    info.changeLifeBy(-1)
})
info.onLifeZero(function on_life_zero() {
    info.setScore(info.score())
    game.over(false, effects.slash)
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function on_on_overlap2(sprite: Sprite, otherSprite: Sprite) {
    otherSprite.destroy(effects.spray, 500)
})
let bogey : Sprite = null
let spacePlan : Sprite = null
spacePlan = sprites.create(img`
        ..fff.........777777....
            ..79ff.......7ff8877....
            ..799ff...777ffff77.....
            ..7899ffff88889999ff....
            ..7889ff8888888899b9f...
            ..c78888888888888b999f..
            .c88f888888888b11199b8f.
            788fffffff888899111b888f
            77777ff888f8888888888887
            .....788889988888888887.
            ....78888997f888888877..
            ...f8888997777777777....
            ...f8888f777f87.........
            ...777777778ff7.........
            .......77778f7..........
            ........77777...........
    `, SpriteKind.Player)
spacePlan.setPosition(0, 60)
controller.moveSprite(spacePlan, 0, 35)
spacePlan.setStayInScreen(true)
info.setLife(3)
info.setScore(0)
let speed = -70
game.onUpdateInterval(1000, function on_update_interval() {
    
    speed += -5
    bogey = sprites.create(img`
            ....................
                    ....................
                    ....................
                    ....................
                    ....................
                    ....eee.............
                    ...eeeee............
                    ..eeee4ee...e.......
                    ..ceeee4ee..e4......
                    ..ceeeee4eecee......
                    ..ceeeeeeeccee......
                    ..ceeeeeee..ee......
                    ..cceeeee...e.......
                    ...cceee............
                    ....cee.............
                    ....................
                    ....................
                    ....................
                    ....................
                    ....................
        `, SpriteKind.Enemy)
    bogey.setVelocity(speed, 0)
    bogey.setPosition(160, randint(10, 100))
    bogey.setFlag(SpriteFlag.AutoDestroy, true)
    info.changeScoreBy(1)
})
